image: "node:8"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm test
    - npm run build
  artifacts:
    paths:
      - node_modules
      - lib
    expire_in: 2 days

test:
  stage: test
  script:
    - ls -la
    - git config -l
    - git branch

deploy:
  stage: deploy
  only:
    refs:
      - master
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - echo "TODO - figure out npm version and publishing with GitLab CI"
