image: "node:8"

stages:
  - build
  - deploy

build:
  script:
    - npm ci
    - npm test

deploy:
  only:
    refs:
      - master
  script:
    - echo "TODO - figure out npm version and publishing with GitLab CI"
